const DQ=s=>document.querySelector(s);let driverUnsub=null,watchId=null,currentUid=null,trackingOrder=null;
const escD=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function showApp(){DQ('#loginGate').style.display='none';DQ('#deliveryApp').style.display='block'}
function showLogin(){DQ('#loginGate').style.display='flex';DQ('#deliveryApp').style.display='none'}
function stopTracking(){if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;trackingOrder=null;DQ('#trackingState').textContent='Location tracking is OFF.'}
function startTracking(order){if(!window.rtdb){alert('Realtime Database is not available.');return} if(!navigator.geolocation){alert('This phone does not support GPS.');return} if(watchId!==null)stopTracking();trackingOrder=order;DQ('#trackingState').innerHTML='<span class="online-dot"></span>Live tracking ON for <b>'+escD(order.orderId)+'</b>';
 watchId=navigator.geolocation.watchPosition(async pos=>{const ref=rtdb.ref('deliveryLocations/'+currentUid);await ref.set({lat:pos.coords.latitude,lng:pos.coords.longitude,accuracy:Math.round(pos.coords.accuracy||0),orderId:order.orderId,isTracking:true,updatedAt:firebase.database.ServerValue.TIMESTAMP});},err=>{DQ('#trackingState').textContent='GPS error: '+err.message;stopTracking()},{enableHighAccuracy:true,maximumAge:5000,timeout:15000});}
async function completeOrder(order,status){if(!confirm('Mark '+order.orderId+' as '+status+'?'))return;try{await db.collection('orders').doc(order.orderId).update({status,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});await db.collection('publicStatuses').doc(order.orderId).set({status,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});if(trackingOrder?.orderId===order.orderId){await rtdb.ref('deliveryLocations/'+currentUid).update({isTracking:false,orderId:null});stopTracking();} }catch(e){alert('Update failed: '+e.message)}}
function renderOrders(items){const el=DQ('#ordersList');if(!items.length){el.innerHTML='<p>No active assigned orders.</p>';return}el.innerHTML=items.map(o=>`<div class="delivery-order"><b>🆔 ${escD(o.orderId)}</b><p>👤 ${escD(o.name)}<br>📞 ${escD(o.phone)}<br>📍 ${escD(o.address)}</p><p>💰 ₹${Number(o.total||0).toLocaleString('en-IN')}<br>📌 ${escD(o.status)}</p><div class="delivery-actions">${o.status==='OUT FOR DELIVERY'?`<button class="primary track-btn" data-id="${escD(o.orderId)}">📍 Start Live Tracking</button><button class="secondary done-btn" data-id="${escD(o.orderId)}">✅ Delivered</button>`:''}${o.status!=='DELIVERED'&&o.status!=='CANCELLED'?`<button class="secondary reached-btn" data-id="${escD(o.orderId)}">🚪 Reached</button>`:''}</div></div>`).join('');items.forEach(o=>{const a=el.querySelector('.track-btn[data-id="'+CSS.escape(o.orderId)+'"]');if(a)a.onclick=()=>startTracking(o);const d=el.querySelector('.done-btn[data-id="'+CSS.escape(o.orderId)+'"]');if(d)d.onclick=()=>completeOrder(o,'DELIVERED');const r=el.querySelector('.reached-btn[data-id="'+CSS.escape(o.orderId)+'"]');if(r)r.onclick=()=>completeOrder(o,'READY');})}
function startOrders(){driverUnsub=db.collection('orders').where('deliveryBoyId','==',currentUid).onSnapshot(s=>{const arr=[];s.forEach(d=>{const o=d.data();if(o.status!=='DELIVERED'&&o.status!=='CANCELLED')arr.push(o)});renderOrders(arr)},e=>DQ('#ordersList').textContent='Could not load orders: '+e.message)}
async function initDriver(user){currentUid=user.uid;const snap=await rtdb.ref('deliveryBoys/'+user.uid).once('value');const p=snap.val()||{};DQ('#driverInfo').textContent='Logged in as '+(p.name||user.email);showApp();startOrders()}
DQ('#loginForm').onsubmit=async e=>{e.preventDefault();try{await auth.signInWithEmailAndPassword(DQ('#email').value.trim(),DQ('#password').value);DQ('#loginError').textContent=''}catch(err){DQ('#loginError').textContent=err.message.replace('Firebase: ','')}};
DQ('#logoutBtn').onclick=async()=>{stopTracking();await auth.signOut()};auth.onAuthStateChanged(u=>u?initDriver(u).catch(e=>DQ('#loginError').textContent=e.message):showLogin());
